-- 코드를 입력하세요
SELECT 
AUTHOR_ID,
AUTHOR_NAME,
CATEGORY,
SUM(A.PRICE*C.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN AUTHOR B USING(AUTHOR_ID)
JOIN BOOK_SALES C USING(BOOK_ID)
WHERE TO_CHAR(SALES_DATE,'YYYY-MM') = '2022-01'
GROUP BY AUTHOR_ID,CATEGORY,AUTHOR_NAME
ORDER BY AUTHOR_ID,CATEGORY DESC;