-- 코드를 입력하세요
SELECT A.CAR_ID,A.CAR_TYPE,
ROUND(DAILY_FEE * (1-(DISCOUNT_RATE*0.01)) * 30) AS FEE
FROM
(SELECT CAR_ID,CAR_TYPE,DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR
WHERE CAR_ID NOT IN
(SELECT CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <='2022-11-30' AND 
END_DATE >= '2022-11-01')
AND CAR_TYPE IN ('세단','SUV')) A
JOIN 
(SELECT CAR_TYPE,DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE DURATION_TYPE = '30일 이상') B
ON A.CAR_TYPE = B.CAR_TYPE
WHERE DAILY_FEE * (1-(DISCOUNT_RATE*0.01)) * 30 >=500000
AND DAILY_FEE * (1-(DISCOUNT_RATE*0.01)) * 30 <= 2000000
ORDER BY 3 DESC,2,1 DESC;