-- 코드를 입력하세요
SELECT CAR_ID,
CAR_TYPE,
(DAILY_FEE*((100-DISCOUNT_RATE)/100))*30 AS FEE
FROM
(SELECT CAR_ID,CAR_TYPE,DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_ID NOT IN
(SELECT CAR_ID
 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
 WHERE TO_CHAR(END_DATE,'YYYY-MM-DD')>='2022-11-01'
 AND TO_CHAR(START_DATE,'YYYY-MM-DD')<='2022-11-30') 
AND CAR_TYPE IN ('세단','SUV')
) A
JOIN 
(SELECT CAR_TYPE,DURATION_TYPE,DISCOUNT_RATE
 FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
 WHERE DURATION_TYPE = '30일 이상' 
) B USING(CAR_TYPE)
WHERE (DAILY_FEE*((100-DISCOUNT_RATE)/100))*30 >= 500000 
AND (DAILY_FEE*((100-DISCOUNT_RATE)/100))*30 < 2000000
ORDER BY FEE DESC,CAR_TYPE,CAR_ID DESC;