-- 코드를 입력하세요
SELECT ANIMAL_ID,A.ANIMAL_TYPE,A.NAME
FROM ANIMAL_INS A JOIN 
ANIMAL_OUTS B USING(ANIMAL_ID)
WHERE A.SEX_UPON_INTAKE LIKE 'Intact%'
AND (B.SEX_UPON_OUTCOME LIKE 'Neutered%' 
OR B.SEX_UPON_OUTCOME LIKE 'Spayed%')
ORDER BY ANIMAL_ID;