-- 코드를 입력하세요
SELECT HISTORY_ID, 
(DAILY_FEE * (100-NVL(DISCOUNT_RATE,0))/100) * USE_DATE AS FEE
FROM (
SELECT A.CAR_ID,
        B.CAR_TYPE,
        B.DAILY_FEE,
        A.HISTORY_ID,
        CASE 
        WHEN (A.END_DATE-A.START_DATE) >= 7 AND 
        (A.END_DATE-A.START_DATE) < 30 THEN '7일 이상'
        WHEN (A.END_DATE-A.START_DATE) >= 30 AND
        (A.END_DATE-A.START_DATE) <90 THEN '30일 이상'
        WHEN (A.END_DATE-A.START_DATE) >= 90 THEN '90일 이상'
        ELSE NULL
        END AS DURATION_TYPE,
        (END_DATE-START_DATE)+1 AS USE_DATE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN
(SELECT * FROM CAR_RENTAL_COMPANY_CAR WHERE CAR_TYPE = '트럭') B
ON A.CAR_ID = B.CAR_ID) C
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
ON C.CAR_TYPE = D.CAR_TYPE
AND C.DURATION_TYPE = D.DURATION_TYPE
ORDER BY FEE DESC,HISTORY_ID DESC;