-- 코드를 입력하세요
WITH TYPE AS (
    SELECT 
    B.CAR_ID,
    A.HISTORY_ID,
    B.DAILY_FEE,
    B.CAR_TYPE,
    DATEDIFF(END_DATE,START_DATE)+1 AS PERIOD,
    CASE WHEN DATEDIFF(END_DATE,START_DATE)+1 >=90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >=30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE,START_DATE)+1 >=7 THEN '7일 이상'
            ELSE 'NONE'
            END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A JOIN 
    CAR_RENTAL_COMPANY_CAR B
    ON A.CAR_ID = B.CAR_ID
    WHERE B.CAR_TYPE = '트럭'
)

            
SELECT A.HISTORY_ID, 
ROUND(A.DAILY_FEE * A.PERIOD * (100- IFNULL(B.DISCOUNT_RATE,0))/100) AS FEE
FROM TYPE A LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.DURATION_TYPE = B.DURATION_TYPE 
AND A.CAR_TYPE = B.CAR_TYPE
ORDER BY 2 DESC,1 DESC;