-- 코드를 입력하세요
SELECT FLAVOR
FROM
(SELECT FLAVOR, A.TOTAL_ORDER +B.TOTAL_ORDER AS TOTAL_ORDER
FROM FIRST_HALF A JOIN
(SELECT FLAVOR,SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY GROUP BY FLAVOR) B
USING(FLAVOR)
ORDER BY TOTAL_ORDER DESC)
WHERE ROWNUM <=3;