-- 코드를 입력하세요
SELECT HOUR,COUNT(A.DATETIME) AS COUNT 
FROM
ANIMAL_OUTS A
RIGHT JOIN
(SELECT LEVEL-1 AS HOUR FROM DUAL CONNECT BY LEVEL<=24) B
ON B.HOUR = TO_CHAR(A.DATETIME,'HH24')
GROUP BY HOUR
ORDER BY HOUR;
