-- 코드를 입력하세요
SELECT MEMBER_NAME,B.REVIEW_TEXT,
TO_CHAR(REVIEW_DATE,'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A JOIN REST_REVIEW B
ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID IN 
(SELECT MEMBER_ID 
 FROM REST_REVIEW GROUP BY MEMBER_ID HAVING COUNT(MEMBER_ID)
= (SELECT MAX(COUNT(MEMBER_ID)) FROM REST_REVIEW GROUP BY MEMBER_ID))
ORDER BY REVIEW_DATE,REVIEW_TEXT
           
